In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('MOA_features_with_descriptors.csv')

In [17]:
df.shape

(1901, 1024)

In [18]:
df

,SMILES,protein_sequence,MOA,MOA_encoded,ECFP_0,ECFP_1,ECFP_2,ECFP_3,ECFP_4,ECFP_5,...,ECFP_1010,ECFP_1011,ECFP_1012,ECFP_1013,ECFP_1014,ECFP_1015,ECFP_1016,ECFP_1017,ECFP_1018,ECFP_1019
0,CC(C)OC(=O)CNC1=CC=CC(=N1)CN(CC2=CC=C(C=C2)N3C...,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Agonist,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CC#CCC(C)C(C=CC1C(CC2C1CC(=CCCCC(=O)O)C2)O)O,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Agonist,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,CCCCCC(C=CC1C(CC(=O)C1CCCCCCC(=O)O)O)O,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Agonist,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,CC1=C2COC(=O)C2=C(C(=C1OC)CC=C(C)CCC(=O)OCCN3C...,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Modulator,10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,CCCCCC(C=CC1C(CC(=O)C1CC=CCCCC(=O)O)O)O,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Antagonist,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,CC1N2C3=CC(=C(C=C3C(=O)C(=C2S1)C(=O)O)F)N4CCN(...,MSDMAERLALHEFTENAYLNYSMYVIMDRALPFIGDGLKPVQRRIV...,Inhibitor,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1897,[H+].C1=CC(=C(C=C1CCC(=O)NCCCCCC(=O)NCCCCC(C(=...,MWNLLHETDSAVATARRPRWLCAGALVLAGGFFLLGFLFGWFIKSS...,Binder,4,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1898,CC1CC(CN1C(=O)CCCCCCCCCCC(=O)NC(COCCC(=O)NCCCN...,MESVVRRCPFLSRVPQAFLQKAGKSLLFYAQNCPKMMEVGAKPAPR...,Inhibitor,9,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,1
1899,CC1C2=NN=C(N2CCN1C(=O)C3=CC=C(C=C3)F)C4=NC(=NS4)C,MATLPAAETWIDGGGGVGADAVNLTASLAAGAATGAVETGWLQLLD...,Antagonist,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1900,C1CC1CN2CCN(CC2)C(=O)C3=CC=C(C=C3)NS(=O)(=O)C4...,MSIQENISSLQLRSWVSKSQRDLAKSILIGAPGGPAGYLRRASVAQ...,Activator,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [19]:
import os
import datetime

path = "MOA_features_with_descriptors.csv"
print("Last modified:",
      datetime.datetime.fromtimestamp(os.path.getmtime(path)))

Last modified: 2026-02-20 16:16:11.154883

In [23]:
df2 = pd.read_csv('MOA_features_with_descriptors.csv')

In [24]:
df2

,SMILES,protein_sequence,MOA,MOA_encoded,ECFP_0,ECFP_1,ECFP_2,ECFP_3,ECFP_4,ECFP_5,...,BertzCT,Kappa1,Kappa2,Kappa3,MaxAbsPartialCharge,MinAbsPartialCharge,MaxPartialCharge,MinPartialCharge,NumBridgeheadAtoms,NumSpiroAtoms
0,CC(C)OC(=O)CNC1=CC=CC(=N1)CN(CC2=CC=C(C=C2)N3C...,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Agonist,1,0,1,0,0,0,0,...,1409.229342,25.986673,11.763014,6.989112,0.461656,0.325122,0.325122,-0.461656,0.0,0.0
1,CC#CCC(C)C(C=CC1C(CC2C1CC(=CCCCC(=O)O)C2)O)O,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Agonist,1,0,1,0,0,0,0,...,594.998843,20.738404,9.943901,5.721733,0.481230,0.302851,0.302851,-0.481230,0.0,0.0
2,CCCCCC(C=CC1C(CC(=O)C1CCCCCCC(=O)O)O)O,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Agonist,1,0,1,0,0,0,0,...,431.802450,21.842017,12.201558,8.634320,0.481230,0.302840,0.302840,-0.481230,0.0,0.0
3,CC1=C2COC(=O)C2=C(C(=C1OC)CC=C(C)CCC(=O)OCCN3C...,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Modulator,10,0,0,0,0,0,0,...,856.216339,23.090884,10.636329,5.566118,0.506590,0.342193,0.342193,-0.506590,0.0,0.0
4,CCCCCC(C=CC1C(CC(=O)C1CC=CCCCC(=O)O)O)O,MGNASNDSQSEDCETRQWLPPGESPAISSVMFSAGVLGNLIALALL...,Antagonist,2,0,1,0,0,0,0,...,468.706971,21.582481,11.984622,8.453347,0.481230,0.302851,0.302851,-0.481230,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,CC1N2C3=CC(=C(C=C3C(=O)C(=C2S1)C(=O)O)F)N4CCN(...,MSDMAERLALHEFTENAYLNYSMYVIMDRALPFIGDGLKPVQRRIV...,Inhibitor,9,0,0,0,0,0,0,...,1368.582788,20.830580,7.521912,3.230652,0.518555,0.477466,0.518555,-0.477466,0.0,0.0
1897,[H+].C1=CC(=C(C=C1CCC(=O)NCCCCCC(=O)NCCCCC(C(=...,MWNLLHETDSAVATARRPRWLCAGALVLAGGFFLLGFLFGWFIKSS...,Binder,4,0,1,0,0,0,0,...,2029.300718,59.642590,32.350222,26.091460,3.000000,0.872231,3.000000,-0.872231,0.0,0.0
1898,CC1CC(CN1C(=O)CCCCCCCCCCC(=O)NC(COCCC(=O)NCCCN...,MESVVRRCPFLSRVPQAFLQKAGKSLLFYAQNCPKMMEVGAKPAPR...,Inhibitor,9,0,0,0,0,1,0,...,2730.252456,104.752987,60.032658,42.372298,0.393567,0.222396,0.222396,-0.393567,0.0,0.0
1899,CC1C2=NN=C(N2CCN1C(=O)C3=CC=C(C=C3)F)C4=NC(=NS4)C,MATLPAAETWIDGGGGVGADAVNLTASLAAGAATGAVETGWLQLLD...,Antagonist,2,0,0,0,0,0,0,...,934.510469,15.824908,5.994923,2.697006,0.326871,0.254030,0.254030,-0.326871,0.0,0.0
1900,C1CC1CN2CCN(CC2)C(=O)C3=CC=C(C=C3)NS(=O)(=O)C4...,MSIQENISSLQLRSWVSKSQRDLAKSILIGAPGGPAGYLRRASVAQ...,Activator,0,0,0,0,0,0,0,...,1226.343840,20.906247,8.519055,4.467118,0.336081,0.263568,0.263568,-0.336081,0.0,0.0

In [25]:
df2.shape

(1901, 3268)

In [29]:
import pandas as pd

print("DATA:", pd.read_csv("/mnt/HDD/Rishabh/MOA_platform/data/MOA_features_with_descriptors.csv").shape)
print("ARTIFACTS:", pd.read_csv("/mnt/HDD/Rishabh/MOA_platform/artifacts/MOA_features_with_descriptors.csv").shape)

DATA: (1901, 3268)
ARTIFACTS: (1901, 3268)

In [27]:
import os
import pandas as pd

# Current working directory
print("Current working directory:", os.getcwd())

# Build absolute paths
data_path = os.path.abspath(
    os.path.join("data", "MOA_features_with_descriptors.csv")
)

artifacts_path = os.path.abspath(
    os.path.join("artifacts", "MOA_features_with_descriptors.csv")
)

print("\nDATA path:", data_path)
print("ARTIFACTS path:", artifacts_path)

# Check existence
print("\nDATA exists?", os.path.exists(data_path))
print("ARTIFACTS exists?", os.path.exists(artifacts_path))

# If files exist, print shapes
if os.path.exists(data_path):
    print("DATA shape:", pd.read_csv(data_path).shape)

if os.path.exists(artifacts_path):
    print("ARTIFACTS shape:", pd.read_csv(artifacts_path).shape)

Current working directory: /mnt/HDD/Rishabh/MOA_platform/data

DATA path: /mnt/HDD/Rishabh/MOA_platform/data/data/MOA_features_with_descriptors.csv
ARTIFACTS path: /mnt/HDD/Rishabh/MOA_platform/data/artifacts/MOA_features_with_descriptors.csv

DATA exists? False
ARTIFACTS exists? False

In [31]:
import pandas as pd

df = pd.read_csv("/mnt/HDD/Rishabh/MOA_platform/data/MOA_features_with_descriptors.csv")

prot_cols = [c for c in df.columns if c.startswith("PROT_")]

print("Number of PROT columns:", len(prot_cols))
print("First 10 PROT columns:", prot_cols[:10])

Number of PROT columns: 1024
First 10 PROT columns: ['PROT_0', 'PROT_1', 'PROT_2', 'PROT_3', 'PROT_4', 'PROT_5', 'PROT_6', 'PROT_7', 'PROT_8', 'PROT_9']

In [32]:
from moa.services.feature_extractor import extract_protein_embedding

seq = "MTEITAAMVKELRESTGAGMMDCKNALSETQHEK"
vec = extract_protein_embedding(seq)

print(type(vec))
print(vec.shape if hasattr(vec, "shape") else vec)

ModuleNotFoundError: No module named 'moa'